export const keywords = [
  "supply partners",
  "horeca",
  "Horeca",
  "HoReCa",
  "restaurants",
  "hotels",
  "heroca",
  "horeca O'zbekistonda",
  "horeca Uzbekistonda",
  "horeca Toshkentda",
  "B2B marketplace",
  "mehmonxona uchun horeca",
  "restaran uhcun horeca",
  "restoran uhcun horeca",
  "mehmonxona hamkorlar",
  "restaran hamkorlar",
  "restoran hamkorlar",
  "umumiy ovqatlanish joylari",
  "housekeeping",
  "xalqaro mehmonxonalar",
  "eng yaxshi mehmonxonalar",
  "top mehmonxonalar",
  "top restaranlar",
  "top restoranlar",
  "mehmonxona uchun kosmetika",
  "food beverage",
  "mehmonxona uchun arxitektura",
  "restaran uchun arxitektura",
  "mehmonxona uchun muhandislik tizimlari",
  "restaran uchun muhandislik tizimlari",
  "restoran uchun muhandislik tizimlari",
  "mehmonxona uchun yong'inga qarshi tizimlar",
  "mehmonxona uchun uskunalar",
  "mehmonxona uchun kerakli jihozlar",
  "mehmonxona uchun yumshoq mebel",
  "mehmonxona uchun mebel",
  "restaran uchun yong'inga qarshi tizimlar",
  "restoran uchun yong'inga qarshi tizimlar",
  "restaran uchun uskunalar",
  "restoran uchun uskunalar",
  "restaran uchun kerakli jihozlar",
  "restoran uchun kerakli jihozlar",
  "restaran uchun yumshoq mebel",
  "restoran uchun yumshoq mebel",
  "restaran uchun mebel",
  "restoran uchun mebel",
  "restoran uchun uskunalar",
  "mehmonxona uchun kir yuvish uskunalari",
  "restaran uchun kir yuvish uskunalari",
  "restoran uchun kir yuvish uskunalari",
  "kommunal xarajatlarni optimallashtirish tizimlari",
  "mehmonxona uchun IT-uskunalari va dasturiy ta'minot",
  "mehmonxona uchun IT-uskunalari",
  "mehmonxona qabul va joylashtirish xizmati",
  "mehmonxona uchun oziq-ovqat",
  "restaran uchun oziq-ovqat",
  "restoran uchun oziq-ovqat",
  "mehmonxona security",
  "restaran security",
  "restoran security",
  "mehmonxonalar uchun konsultatsiya",
  "mehmonxona xodimlari uchun konsultatsiya",
  "mehmonxona biznesi qanday bo'ladi",
  "mehmonxona biznesini nimadan boshlash kerak",
  "mehmonxonani qanday jihozlar bilan jihozlash kerak",
  "mehmonxona biznesida ishonchli hamkorlarni qayerdan topsa bo'ladi",
  "restaranlar uchun konsultatsiya",
  "restoranlar uchun konsultatsiya",
  "restaran xodimlari uchun konsultatsiya",
  "restoran xodimlari uchun konsultatsiya",
  "restaran biznesi qanday bo'ladi",
  "restoran biznesi qanday bo'ladi",
  "restaran biznesini nimadan boshlash kerak",
  "restoran biznesini nimadan boshlash kerak",
  "restaranni qanday jihozlar bilan jihozlash kerak",
  "restoranni qanday jihozlar bilan jihozlash kerak",
  "restaran biznesida ishonchli hamkorlarni qayerdan topsa bo'ladi",
  "restoran biznesida ishonchli hamkorlarni qayerdan topsa bo'ladi",
  "mehmonxonani qanday qurish kerak",
  "restaranni qanday qurish",
  "restoranni qanday qurish",
  "qurilayotgan mehmonxonalar uchun konsultatsiya",
  "qurilayotgan restaranlar uchun konsultatsiya",
  "qurilayotgan restoranlar uchun konsultatsiya",
  "mehmonxonalar uchun gigiena vositalari",
  "restaranlar uchun gigiena vositalari",
  "restoranlar uchun gigiena vositalari",
  "mehmonxona uchun interyer dizayner",
  "restaran uchun interyer dizayner",
  "restoran uchun interyer dizayner",
  "xalqaro mehmonxona brendlari bilan muzokaralar olib borish",
  "mehmonxona uchun kosmetika tanlashda nimalarga e'tibor berish kerak",
  "catering xizmatlari",
  "to'y va ziyofatlarni tashkil qilish",
  "o'zbekistonda FF&E va OS&E eng yaxshi narxlarda qayerda sotib olinadi",
  "Toshkentda mehmonxona jihozlari uchun ishonchli yetkazib beruvchi",
  "restoran jihozlari do'koni",
  "kir-yuvish jihozlari bo'yicha mutaxassislar",
  "mehmonxona uchun konsalting xizmatlari",
  "mehmonxona uchun jihozlar",
  "restaran uchun jihozlar",
  "restoran uchun jihozlar",
  "restoran uchun jihozlar Toshkentda",
  "mehmonxona uchun ko'rpa yostiq choyshab",
  "oshxonani tashkil qilish",
  "kirxonani tashkil qilish",
  "xonalarni tozalash",
  "horeca hamkorlar",
  "mehmonxona jihozlarini yetkazib beruvchilar",
  "restaran jihozlarini yetkazib beruvchilar",
  "restoran jihozlarini yetkazib beruvchilar",
  "mehmonxona",
  "restoran",
  "xizmatlar",
  "Yetkazish va to'lash",
  "horeca uchun b2b marketpleys o'zbekistonda",
  "Bu yerda siz sifatli mahsulotlarni yetakchi ishlab chiqaruvchilardan to'g'ridan-to'g'ri va aniq yetkazib berish muddatlari bilan arzon narxlarda sotib olishingiz mumkin",
  "Mehmonxona. Yangi qurilayotgan",
  "Bizning B2B saytimizda siz xalqaro mehmonxona brendlari tomonidan har qanday miqyosdagi va yulduzli loyihalar uchun akkreditatsiyadan o'tgan mahsulotlarni xarid qilishingiz mumkin",
  "FF&E va OS&E",
  "Muhandislik tizimlari",
  "Yong'inga qarshi tizimlar, uskunalar va mebel",
  "Restoran va barlar uchun uskunalar",
  "Kir yuvish uskunalari",
  "mehmonxona uchun kir yuvish vositalari",
  "mehmonxona uchun kir yuvish vositalari Toshkentda",
  "Kommunal xarajatlarni optimallashtirish tizimlari",
  "IT-uskunalari va dasturiy ta'minot",
  "HORECA biznesingizni ishonchli hamkor bilan rivojlantiring",
  "Mehmonxona. Faoliyatdagi",
  "Restoran. Qurilayotgan va faoliyatdagi",
  "Bizning maydonchamizda siz restoran biznesi uchun professional uskunalarni sotib olishingiz mumkin",
  "Tozalash uskunalari va professional kimyo",
  "Bir martalik idishlar va qadoqlash",
  "Mehmonxona va restoran biznesi uchun xizmatlar",
  "Mehmonxona va restoran biznesi uchun xizmatlar Toshkentda",
  "Akkreditatsiyadan o'tgan interyer dizaynerlarini tanlash",
  "Loyiha uchun texnik maslahatchini tanlash (loyiha menejeri)",
  "Maxsus maslahatchilarni tanlash (yong'in xavfsizligi, ovoz izolyatsiyasi, oshxona texnologiyasi va boshqalar bo'yicha)",
  "mehmonxona uchun mahsulotlar va xizmatlar",
  "restaran uchun mahsulotlar va xizmatlar",
  "restoran uchun mahsulotlar va xizmatlar",
  "mehmonxona uchun mahsulotlar va xizmatlar Toshkentda",
  "restaran uchun mahsulotlar va xizmatlar Toshkentda",
  "restoran uchun mahsulotlar va xizmatlar Toshkentda",
  "bar uchun mahsulotlar va xizmatlar Toshkentda",
  "Toshkentda HORECA platformasi",
  "Horeca oshxona uchun tovarlar",
  "Mehmonxonalar, restoranlar, barlar uchun xizmatlar",
  "Mehmonxonalar, restoranlar, barlar uchun xizmatlar Toshkentda",
  "HoReCa uchun xizmat ko'rsatuvchi",
  "HoReCa uchun xizmat ko'rsatuvchi Toshkentda",
  "HoReCa uchun tovarlarning ulgurji savdosi",
  "HoReCa uchun tovarlarning ulgurji savdosi Toshkentda",
  "HoReCa uchun professional jihozlar",
  "HoReCa uchun professional jihozlar Toshkentda",
  "HoReCa uchun inventar",
  "HoReCa uchun inventar Toshkentda",
  "HoReCa uchun oshxona buyumlari",
  "HoReCa uchun oshxona buyumlari Toshkentda",
  "HoReCa uchun mebel",
  "HoReCa uchun mebel Toshkentda",
  "HoReCa uchun idishlar",
  "HoReCa uchun idishlar Toshkentda",
  "HoReCa uchun tozalash vositalari",
  "HoReCa uchun tozalash vositalari Toshkentda",
  "HoReCa uchun servis xizmati",
  "HoReCa uchun servis xizmati Toshkentda",
  "HoReCa uchun logistika",
  "HoReCa uchun logistika Toshkentda",
  "HoReCa uchun konsalting",
  "HoReCa uchun konsalting Toshkentda",
  "Mehmonxonalar uchun xizmatlar",
  "Mehmonxonalar uchun xizmatlar Toshkentda",
  "Mehmonxonalar uchun tovarlarning ulgurji savdosi",
  "Mehmonxonalar uchun tovarlarning ulgurji savdosi Toshkentda",
  "Mehmonxonalar uchun professional jihozlar",
  "Mehmonxonalar uchun professional jihozlar Toshkentda",
  "Mehmonxonalar uchun inventar",
  "Mehmonxonalar uchun inventar Toshkentda",
  "Mehmonxona hammomlari uchun buyumlar",
  "Mehmonxona hammomlari uchun buyumlar Toshkentda",
  "Mehmonxona mebellari",
  "Mehmonxona mebellari Toshkentda",
  "Mehmonxona uchun choyshab va sochiqlar",
  "Mehmonxona uchun choyshab va sochiqlar Toshkentda",
  "Mehmonxona uchun tozalash vositalari",
  "Mehmonxona uchun tozalash vositalari Toshkentda",
  "Mehmonxona uchun servis xizmati",
  "Mehmonxona uchun servis xizmati Toshkentda",
  "Mehmonxona taʼmirlash va texnik xizmat ko'rsatish",
  "Mehmonxona taʼmirlash va texnik xizmat ko'rsatish Toshkentda",
  "Mehmonxona boshqaruv tizimi",
  "Mehmonxona bronlash tizimi",
  "Mehmonxona uchun konsalting",
  "Mehmonxona uchun konsalting Toshkentda",
  "Restoranlar uchun xizmatlar",
  "Restoranlar uchun xizmatlar Toshkentda",
  "Restoranlar uchun tovarlarning ulgurji savdosi",
  "Restoranlar uchun tovarlarning ulgurji savdosi Toshkentda",
  "Restoranlar uchun professional jihozlar",
  "Restoranlar uchun professional jihozlar Toshkentda",
  "Restoranlar uchun inventar",
  "Restoranlar uchun inventar Toshkentda",
  "Restoranlar uchun idishlar",
  "Restoranlar uchun idishlar Toshkentda",
  "Restoranlar uchun mebel",
  "Restoranlar uchun mebel Toshkentda",
  "Restoranlar uchun tozalash vositalari",
  "Restoranlar uchun tozalash vositalari Toshkentda",
  "Restoranlar uchun taʼmirlash va texnik xizmat ko'rsatish",
  "Restoranlar uchun taʼmirlash va texnik xizmat ko'rsatish Toshkentda",
  "Restoran boshqaruv tizimi",
  "Restoran uchun konsalting",
  "Restoran uchun konsalting Toshkentda",
  "Toshkentdagi mehmonxonalar, restoranlar, barlar uchun xizmatlar",
  "Toshkentda HoReCa uchun xizmat ko'rsatuvchi",
  "Toshkentda HoReCa uchun tovarlarning ulgurji savdosi",
  "Toshkentda HoReCa uchun professional jihozlar",
  "Toshkentda HoReCa uchun inventar",
  "HoReCa uchun chegirmalar",
  "HoReCa uchun aksiyalar",
  "HoReCa uchun tovarlar yetkazib berish",
  "HoReCa uchun internet-do'kon",
  "HoReCa uchun blog",
  "",
  // ----------------------------
  "Как правильно выбрать оборудование для производства продуктов питания и напитков для вашего отеля",
  "На что обратить внимание при выборе косметики для отеля",
  "Партнерство отеля и поставщика: 5 важных советов, как найти наилучшее решение",
  "Рекомендации поставщиков гостиничных услуг для успешного курортного сезона",
  "The supply",
  "Мебель для HORECA в Ташкенте и Узбекистане",
  "Horeca Trade kompaniya haqida to'liq ma'lumot",
  "Диваны для Horeca в Ташкенте и Узбекистане",
  "The hotel supply",
  "furnishings, decor, fixtures",
  "hotel supplier partnership",
  "elevate hygiene with premium hotel & restaurant supplies",
  "hotel amenities supplier",
  "revolutionizing weddings",
  "achieving sustainability & eco-friendless a guide for luxury hotels and resorts",
  "how to chooose the right food & beverage equipment to your hotel",
  "boost hygiene standards using quality hotel & restaurant supplies",
  "Поставщики (противопожарных дверей, замков в гостевые номера, инженерных систем, мебели, постельного белья, матрасов, аменитис и др.)",
  "Оборудование для ресторанов и баров",
  "Оборудование для прачечных",
  "Системы для оптимизации коммунальных расходов",
  "Тренинги для персонала отелей",
  "ИТ-оборудование и решения",
  "Консультанты (по акустике, свету, звуку, пожарной безопасности, технологии кухни, по искусству и др.)",
  "Архитекторы",
  "Дизайнеры интерьеров",
  "Гостиничные консультанты для исследования рынка",
  "Управляющие компании",
  "Независимые генеральные управляющие",
  "На этапе проектирования и строительства объекта, вместе с собственником, команда Supply Partners разрабатывает концепцию, оценивает конъюнктуру рынка и готовит прогноз достижимых финансовых показателей",
  "Supply Partners приглашает всех предпринимателей, которые хотят начать гостиничный, кафе, ресторанный бизнес и в настоящее время ведут его. Мы будем очень рады работать с вами",
  "laundry",
  "b2b-площадка для horeca в узбекистане",
  "B2B-ПЛОЩАДКА ДЛЯ HORECA В УЗБЕКИСТАНЕ",
  "Здесь вы приобретаете качественные товары по разумным ценам напрямую от ведущих производителей с четкими сроками доставки и в нужное вам время",
  "Отели. Новое строительство",
  "На нашей B2B-площадке вы сможете приобрести товары, которые аккредитованы международными гостиничными брендами для проектов любого масштаба и звездности.",
  "Инженерных систем",
  "Противопожарных систем, оборудования и мебели",
  "Оборудования для ресторанов и баров",
  "Оборудования для прачечных",
  "Систем для оптимизации коммунальных расходов",
  "ИТ-оборудования и программного обеспечения",
  "Развивайте свой бизнес в HORECA с надежным партнером. Сделайте запрос уже сейчас и получите каталог с расценками на товары для заказа.",
  "Противопожарных систем, оборудования и мебели в ташкенте",
  "Оборудования для ресторанов и баров в ташкенте",
  "Оборудования для прачечных в ташкенте",
  "Систем для оптимизации коммунальных расходов в ташкенте",
  "ИТ-оборудования и программного обеспечения в ташкенте",
  "Развивайте свой бизнес в HORECA с надежным партнером. Сделайте запрос уже сейчас и получите каталог с расценками на товары для заказа",
  "Отели. Действующие",
  "Если вы бутик-отель до 100 номеров или же отель полного цикла от 100 номеров и выше, на нашей площадке вы сможете приобрести товары, которые аккредитованы международными гостиничными брендами для следующих служб вашего отеля",
  "Служба приема и размещения",
  "Хозяйственная служба или служба эксплуатации номерного фонда",
  "Противопожарных систем, оборудования и мебели",
  "Инженерная служба",
  "Служба питания",
  "Служба безопасности",
  "Служба приема и размещения в ташкенте",
  "Хозяйственная служба или служба эксплуатации номерного фонда в ташкенте",
  "Противопожарных систем, оборудования и мебели в ташкенте",
  "Инженерная служба в ташкенте",
  "Служба питания в ташкенте",
  "Служба безопасности в ташкенте",
  "Рестораны и бары. Строящиеся и действующие",
  "На нашей площадке вы сможете приобрести профессиональное оборудование для ресторанного бизнеса",
  "Гигиена и расходники",
  "Инвентарь для уборки и проффесиональная химия",
  "Одноразовая посуда и упаковка",
  "Услуги. Для гостиничного ресторанного бизнеса",
  "Подбор международного гостиничного консультанта для исследования рынка",
  "Подбор архитектора для проекта",
  "Подбор аккредитованных дизайнеров интерьеров",
  "Подбор технического консультанта для проекта (проектного менеджера)",
  "Подбор специализированных консультантов (по пожарной безопасности, шумоизоляции, технологии кухни и др",
  "Подбор управляющих компаний",
  "Подбор генерального управляющего",
  "Подбор и ведение переговоров с международными гостиничными брендами",
  "Тренинги «a la carte» для персонала отеля, ресторана или бара (revenue management и др.)",
  "Доставка и оплата. Товаров и услуг.",
  "Отели",
  "Рестораны",
  "Услуги",
  "Доставка и оплата",
  "Контакты",
  "Отели в ташкенте",
  "Рестораны в ташкенте",
  "услуги для отеля",
  "услуги для ресторанов",
  "услуги для бара",
  "услуги для отеля в ташкенте",
  "услуги для ресторанов в ташкенте",
  "услуги для бара в ташкенте",
  "продукты для отеля",
  "продукты для ресторанов",
  "продукты для бара",
  "продукты для отеля в ташкенте",
  "продукты для ресторанов в ташкенте",
  "продукты для бара в ташкенте",
  "поставщики для отеля",
  "поставщики для ресторанов",
  "поставщики для баров",
  "поставщики для отеля в ташкенте",
  "поставщики для ресторанов в ташкенте",
  "поставщики для баров в ташкенте",
  "HoReCa (Хорека)",
  "Что такое Хорека",
  "Кто относится к HoReCa",
  "Почему Хорека так называется",
  "Гостинично-ресторанный бизнес",
  "Гостинично-ресторанный бизнес в ташкенте",
  "Услуги для отелей, ресторанов, баров",
  "Услуги для отелей, ресторанов, баров в ташкенте",
  "Поставщик услуг для HoReCa",
  "Поставщик услуг для HoReCa в ташкенте",
  "Оптовая продажа товаров для HoReCa",
  "Оптовая продажа товаров для HoReCa в ташкенте",
  "Профессиональное оборудование для HoReCa",
  "Профессиональное оборудование для HoReCa в ташкенте",
  "Инвентарь для HoReCa",
  "Инвентарь для HoReCa в ташкенте",
  "Товары для кухни HoReCa",
  "Товары для кухни HoReCa в ташкенте",
  "Мебель для HoReCa",
  "Мебель для HoReCa в ташкенте",
  "Посуда для HoReCa",
  "Посуда для HoReCa в ташкенте",
  "Текстиль для HoReCa",
  "Текстиль для HoReCa в ташкенте",
  "Чистящие средства для HoReCa",
  "Чистящие средства для HoReCa в ташкенте",
  "Сервисное обслуживание HoReCa",
  "Сервисное обслуживание HoReCa в ташкенте",
  "Консалтинг для HoReCa",
  "Консалтинг для HoReCa в ташкенте",
  "Оптовая продажа товаров для отелей",
  "Оптовая продажа товаров для отелей в ташкенте",
  "Профессиональное оборудование для отелей",
  "Профессиональное оборудование для отелей в ташкенте",
  "Инвентарь для отелей",
  "Инвентарь для отелей в ташкенте",
  "Товары для ванной комнаты отеля",
  "Товары для ванной комнаты отеля в ташкенте",
  "Мебель для отеля",
  "Мебель для отеля в ташкенте",
  "Постельное белье и полотенца для отеля",
  "Постельное белье и полотенца для отеля в ташкенте",
  "Чистящие средства для отеля",
  "Чистящие средства для отеля в ташкенте",
  "Сервисное обслуживание отеля",
  "Сервисное обслуживание отеля в ташкенте",
  "Ремонт и техническое обслуживание отеля",
  "Ремонт и техническое обслуживание отеля в ташкенте",
  "Система управления отелем",
  "Система управления отелем в ташкенте",
  "Кассовый аппарат для отеля",
  "Кассовый аппарат для отеля в ташкенте",
  "Система бронирования отеля",
  "Система бронирования отеля в ташкенте",
  "Консалтинг для отеля",
  "Консалтинг для отеля в ташкенте",
  "Услуги для ресторанов",
  "Услуги для ресторанов в ташкенте",
  "Оптовая продажа товаров для ресторанов",
  "Оптовая продажа товаров для ресторанов в ташкенте",
  "Профессиональное оборудование для ресторанов",
  "Профессиональное оборудование для ресторанов в ташкенте",
  "Инвентарь для ресторанов",
  "Инвентарь для ресторанов в ташкенте",
  "Посуда для ресторанов",
  "Посуда для ресторанов в ташкенте",
  "Мебель для ресторанов",
  "Мебель для ресторанов в ташкенте",
  "Текстиль для ресторанов",
  "Текстиль для ресторанов в ташкенте",
  "Чистящие средства для ресторанов",
  "Чистящие средства для ресторанов в ташкенте",
  "Сервисное обслуживание ресторанов",
  "Сервисное обслуживание ресторанов в ташкенте",
  "Ремонт и техническое обслуживание ресторанов",
  "Ремонт и техническое обслуживание ресторанов в ташкенте",
  "Система управления рестораном",
  "Система управления рестораном в ташкенте",
  "Кассовый аппарат для ресторана",
  "Кассовый аппарат для ресторана в ташкенте",
  "Система бронирования столиков",
  "Система бронирования столиков в ташкенте",
  "Консалтинг для ресторана",
  "Консалтинг для ресторана в ташкенте",
  "Услуги для отелей, ресторанов, баров в Ташкенте",
  "Поставщик услуг для HoReCa в Ташкенте",
  "Оптовая продажа товаров для HoReCa в Ташкенте",
  "Профессиональное оборудование для HoReCa в Ташкенте",
  "Инвентарь для HoReCa в Ташкенте",
  "Скидки для HoReCa",
  "Акции для HoReCa",
  "Доставка товаров для HoReCa",
  "Интернет-магазин для HoReCa",
  "Блог для HoReCa",
  "Отзывы о HoReCa",
  "",
  "",
  "",
  // -----------------------------------------------------
  "Hospitality services for hotels, restaurants, bars",
  "Hospitality services for hotels, restaurants, bars in Tashkent",
  "HoReCa supplier",
  "HoReCa supplier in Tashkent",
  "Wholesale HoReCa supplies",
  "Wholesale HoReCa supplies in Tashkent",
  "Professional HoReCa equipment",
  "Professional HoReCa equipment in Tashkent",
  "HoReCa supplies",
  "HoReCa supplies in Tashkent",
  "HoReCa kitchen supplies",
  "HoReCa kitchen supplies in Tashkent",
  "HoReCa furniture",
  "HoReCa furniture in Tashkent",
  "HoReCa tableware",
  "HoReCa tableware in Tashkent",
  "HoReCa textiles",
  "HoReCa textiles in Tashkent",
  "HoReCa cleaning supplies",
  "HoReCa cleaning supplies in Tashkent",
  "HoReCa service outsourcing",
  "HoReCa service outsourcing in Tashkent",
  "HoReCa logistics",
  "HoReCa logistics in Tashkent",
  "HoReCa consulting",
  "HoReCa consulting in Tashkent",
  "Hotel services",
  "Hotel services in Tashkent",
  "Wholesale hotel supplies",
  "Wholesale hotel supplies in Tashkent",
  "Professional hotel equipment",
  "Professional hotel equipment in Tashkent",
  "Hotel supplies",
  "Hotel supplies in Tashkent",
  "Hotel bathroom amenities",
  "Hotel bathroom amenities in Tashkent",
  "Hotel furniture",
  "Hotel furniture in Tashkent",
  "Hotel bed linen and towels",
  "Hotel bed linen and towels in Tashkent",
  "Hotel cleaning supplies",
  "Hotel cleaning supplies in Tashkent",
  "Hotel service outsourcing",
  "Hotel service outsourcing in Tashkent",
  "Hotel maintenance and repair",
  "Hotel maintenance and repair in Tashkent",
  "Hotel Property Management System",
  "Hotel Property Management System in Tashkent",
  "Hotel cash register system",
  "Hotel cash register system in Tashkent",
  "Hotel reservation system",
  "Hotel reservation system in Tashkent",
  "Hotel consulting",
  "Hotel consulting in Tashkent",
  "Restaurant services",
  "Restaurant services in Tashkent",
  "Wholesale restaurant supplies",
  "Wholesale restaurant supplies in Tashkent",
  "Professional restaurant equipment",
  "Professional restaurant equipment in Tashkent",
  "Restaurant supplies",
  "Restaurant supplies in Tashkent",
  "Restaurant tableware",
  "Restaurant tableware in Tashkent",
  "Restaurant furniture",
  "Restaurant furniture in Tashkent",
  "Restaurant cleaning supplies",
  "Restaurant cleaning supplies in Tashkent",
  "Restaurant service outsourcing",
  "Restaurant service outsourcing in Tashkent",
  "Restaurant maintenance and repair",
  "Restaurant maintenance and repair in Tashkent",
  "Restaurant Point of Sale System",
  "Restaurant Point of Sale System in Tashkent",
  "Restaurant consulting",
  "Restaurant consulting in Tashkent",
  "HoReCa discounts",
  "HoReCa promotions",
  "HoReCa supplies delivery",
  "HoReCa online store",
  "HoReCa blog",
  "HoReCa discounts in Tashkent",
  "HoReCa promotions in Tashkent",
  "HoReCa supplies delivery in Tashkent",
  "HoReCa online store in Tashkent",
  "HoReCa blog in Tashkent",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  // -------------------
  "ҳореcа",
  "рестораны",
  "ҳотел",
  "ҳероcа",
  "ҳореcа Ўзбекистонда",
  "ҳореcа Узбекистонда",
  "ҳореcа Тошкентда",
  "Б2Б маркетплаcе",
  "меҳмонхона учун ҳореcа",
  "рестаран уҳcун ҳореcа",
  "ресторан уҳcун ҳореcа",
  "меҳмонхона ҳамкорлар",
  "рестаран ҳамкорлар",
  "ресторан ҳамкорлар",
  "умумий овқатланиш жойлари",
  "ҳоусекеепинг",
  "халқаро меҳмонхоналар",
  "енг яхши меҳмонхоналар",
  "топ меҳмонхоналар",
  "топ рестаранлар",
  "топ ресторанлар",
  "меҳмонхона учун косметика",
  "фоод бевераже",
  "меҳмонхона учун архитектура",
  "рестаран учун архитектура",
  "ресторан учун архитектура",
  "меҳмонхона учун муҳандислик тизимлари",
  "рестаран учун муҳандислик тизимлари",
  "ресторан учун муҳандислик тизимлари",
  "меҳмонхона учун ёнғинга қарши тизимлар",
  "меҳмонхона учун ускуналар",
  "меҳмонхона учун керакли жиҳозлар",
  "меҳмонхона учун юмшоқ мебел",
  "меҳмонхона учун мебел",
  "рестаран учун ёнғинга қарши тизимлар",
  "ресторан учун ёнғинга қарши тизимлар",
  "рестаран учун ускуналар",
  "ресторан учун ускуналар",
  "рестаран учун керакли жиҳозлар",
  "ресторан учун керакли жиҳозлар",
  "рестаран учун юмшоқ мебел",
  "ресторан учун юмшоқ мебел",
  "рестаран учун мебел",
  "ресторан учун мебел",
  "ресторан учун ускуналар",
  "меҳмонхона учун кир ювиш ускуналари",
  "рестаран учун кир ювиш ускуналари",
  "ресторан учун кир ювиш ускуналари",
  "коммунал харажатларни оптималлаштириш тизимлари",
  "меҳмонхона учун ИТ-ускуналари ва дастурий таъминот",
  "меҳмонхона учун ИТ-ускуналари",
  "меҳмонхона қабул ва жойлаштириш хизмати",
  "меҳмонхона учун озиқ-овқат",
  "рестаран учун озиқ-овқат",
  "ресторан учун озиқ-овқат",
  "меҳмонхоналар учун консултация",
  "меҳмонхона ходимлари учун консултация",
  "меҳмонхона бизнеси қандай бўлади",
  "меҳмонхона бизнесини нимадан бошлаш керак",
  "меҳмонхонани қандай жиҳозлар билан жиҳозлаш керак",
  "меҳмонхона бизнесида ишончли ҳамкорларни қайердан топса бўлади",
  "рестаранлар учун консултация",
  "ресторанлар учун консултация",
  "рестаран ходимлари учун консултация",
  "ресторан ходимлари учун консултация",
  "рестаран бизнеси қандай бўлади",
  "ресторан бизнеси қандай бўлади",
  "рестаран бизнесини нимадан бошлаш керак",
  "ресторан бизнесини нимадан бошлаш керак",
  "рестаранни қандай жиҳозлар билан жиҳозлаш керак",
  "ресторанни қандай жиҳозлар билан жиҳозлаш керак",
  "рестаран бизнесида ишончли ҳамкорларни қайердан топса бўлади",
  "ресторан бизнесида ишончли ҳамкорларни қайердан топса бўлади",
  "меҳмонхонани қандай қуриш керак",
  "рестаранни қандай қуриш",
  "ресторанни қандай қуриш",
  "қурилаётган меҳмонхоналар учун консултация",
  "қурилаётган рестаранлар учун консултация",
  "қурилаётган ресторанлар учун консултация",
  "меҳмонхоналар учун гигиена воситалари",
  "рестаранлар учун гигиена воситалари",
  "ресторанлар учун гигиена воситалари",
  "меҳмонхона учун интерйер дизайнер",
  "рестаран учун интерйер дизайнер",
  "ресторан учун интерйер дизайнер",
  "халқаро меҳмонхона брендлари билан музокаралар олиб бориш",
  "меҳмонхона учун косметика танлашда нималарга еътибор бериш керак",
  "cатеринг хизматлари",
  "тўй ва зиёфатларни ташкил қилиш",
  "тўй ва зиёфатларни ташкил қилиш Мехмонхонада",
  "тўй ва зиёфатларни ташкил қилиш Тошкентда",
  "ўзбекистонда ФФ&Е ва ОС&Е енг яхши нархларда қайерда сотиб олинади",
  "Тошкентда меҳмонхона жиҳозлари учун ишончли йетказиб берувчи",
  "ресторан жиҳозлари дўкони",
  "кир-ювиш жиҳозлари бўйича мутахассислар",
  "меҳмонхона учун консалтинг хизматлари",
  "меҳмонхона учун жиҳозлар",
  "рестаран учун жиҳозлар",
  "ресторан учун жиҳозлар",
  "меҳмонхона учун кўрпа ёстиқ чойшаб",
  "ошхонани ташкил қилиш",
  "кирхонани ташкил қилиш",
  "хоналарни тозалаш",
  "ҳореcе ҳамкорлар",
  "меҳмонхона жиҳозларини йетказиб берувчилар",
  "рестаран жиҳозларини йетказиб берувчилар",
  "ресторан жиҳозларини йетказиб берувчилар",
  "меҳмонхона",
  "ресторан",
  "хизматлар",
  "Йетказиш ва тўлаш",
  "ҳореcа учун б2б маркетплейс ўзбекистонда",
  "Бу йерда сиз сифатли маҳсулотларни йетакчи ишлаб чиқарувчилардан тўғридан-тўғри ва аниқ йетказиб бериш муддатлари билан арзон нархларда сотиб олишингиз мумкин",
  "Меҳмонхона. Янги қурилаётган",
  "Бизнинг Б2Б сайтимизда сиз халқаро меҳмонхона брендлари томонидан ҳар қандай миқёсдаги ва юлдузли лойиҳалар учун аккредитациядан ўтган маҳсулотларни харид қилишингиз мумкин",
  "ФФ&Е ва ОС&Е",
  "Муҳандислик тизимлари",
  "Ёнғинга қарши тизимлар, ускуналар ва мебел",
  "Кир ювиш ускуналари",
  "меҳмонхона учун кир ювиш воситалари",
  "меҳмонхона учун кир ювиш воситалари Тошкентда",
  "Коммунал харажатларни оптималлаштириш тизимлари",
  "ИТ-ускуналари ва дастурий таъминот",
  "ҲОРЕCA бизнесингизни ишончли ҳамкор билан ривожлантиринг",
  "Меҳмонхона. Фаолиятдаги",
  "Ресторан. Қурилаётган ва фаолиятдаги",
  "Бизнинг майдончамизда сиз ресторан бизнеси учун профессионал ускуналарни сотиб олишингиз мумкин",
  "Тозалаш ускуналари ва профессионал кимё",
  "Бир марталик идишлар ва қадоқлаш",
  "Меҳмонхона ва ресторан бизнеси учун хизматлар",
  "Меҳмонхона ва ресторан бизнеси учун хизматлар Тошкентда",
  "Aккредитациядан ўтган интерйер дизайнерларини танлаш",
  "Лойиҳа учун техник маслаҳатчини танлаш (лойиҳа менежери)",
  "Махсус маслаҳатчиларни танлаш (ёнғин хавфсизлиги, овоз изоляцияси, ошхона технологияси ва бошқалар бўйича)",
  "меҳмонхона учун маҳсулотлар ва хизматлар",
  "рестаран учун маҳсулотлар ва хизматлар",
  "ресторан учун маҳсулотлар ва хизматлар",
  "бар учун маҳсулотлар ва хизматлар",
  "меҳмонхона учун маҳсулотлар ва хизматлар Тошкентда",
  "рестаран учун маҳсулотлар ва хизматлар Тошкентда",
  "ресторан учун маҳсулотлар ва хизматлар Тошкентда",
  "бар учун маҳсулотлар ва хизматлар Тошкентда",
  "Тошкентда ҲОРЕCA платформаси",
  "Ҳореcа ошхона учун товарлар",
  "Меҳмонхоналар, ресторанлар, барлар учун хизматлар",
  "Меҳмонхоналар, ресторанлар, барлар учун хизматлар Тошкентда",
  "ҲоРеCа учун хизмат кўрсатувчи",
  "ҲоРеCа учун хизмат кўрсатувчи Тошкентда",
  "ҲоРеCа учун товарларнинг улгуржи савдоси",
  "ҲоРеCа учун товарларнинг улгуржи савдоси Тошкентда",
  "ҲоРеCа учун профессионал жиҳозлар",
  "ҲоРеCа учун профессионал жиҳозлар Тошкентда",
  "ҲоРеCа учун инвентар",
  "ҲоРеCа учун инвентар Тошкентда",
  "ҲоРеCа учун ошхона буюмлари",
  "ҲоРеCа учун ошхона буюмлари Тошкентда",
  "ҲоРеCа учун мебел",
  "ҲоРеCа учун мебел Тошкентда",
  "ҲоРеCа учун идишлар",
  "ҲоРеCа учун идишлар Тошкентда",
  "ҲоРеCа учун тозалаш воситалари",
  "ҲоРеCа учун тозалаш воситалари Тошкентда",
  "ҲоРеCа учун сервис хизмати",
  "ҲоРеCа учун сервис хизмати Тошкентда",
  "ҲоРеCа учун логистика",
  "ҲоРеCа учун логистика Тошкентда",
  "ҲоРеCа учун консалтинг",
  "ҲоРеCа учун консалтинг Тошкентда",
  "Меҳмонхоналар учун хизматлар",
  "Меҳмонхоналар учун хизматлар Тошкентда",
  "Меҳмонхоналар учун товарларнинг улгуржи савдоси",
  "Меҳмонхоналар учун товарларнинг улгуржи савдоси Тошкентда",
  "Меҳмонхоналар учун профессионал жиҳозлар",
  "Меҳмонхоналар учун профессионал жиҳозлар Тошкентда",
  "Меҳмонхоналар учун инвентар",
  "Меҳмонхоналар учун инвентар Тошкентда",
  "Меҳмонхона ҳаммомлари учун буюмлар",
  "Меҳмонхона ҳаммомлари учун буюмлар Тошкентда",
  "Меҳмонхона мебеллари",
  "Меҳмонхона мебеллари Тошкентда",
  "Меҳмонхона учун чойшаб ва сочиқлар",
  "Меҳмонхона учун чойшаб ва сочиқлар Тошкентда",
  "Меҳмонхона учун тозалаш воситалари",
  "Меҳмонхона учун тозалаш воситалари Тошкентда",
  "Меҳмонхона учун сервис хизмати",
  "Меҳмонхона учун сервис хизмати Тошкентда",
  "Меҳмонхона таъмирлаш ва техник хизмат кўрсатиш",
  "Меҳмонхона таъмирлаш ва техник хизмат кўрсатиш Тошкентда",
  "Меҳмонхона бошқарув тизими",
  "Меҳмонхона бронлаш тизими",
  "Меҳмонхона учун консалтинг",
  "Меҳмонхона учун консалтинг Тошкентда",
  "Ресторанлар учун хизматлар",
  "Ресторанлар учун хизматлар Тошкентда",
  "Ресторанлар учун товарларнинг улгуржи савдоси",
  "Ресторанлар учун товарларнинг улгуржи савдоси Тошкентда",
  "Ресторанлар учун профессионал жиҳозлар",
  "Ресторанлар учун профессионал жиҳозлар Тошкентда",
  "Ресторанлар учун инвентар",
  "Ресторанлар учун инвентар Тошкентда",
  "Ресторанлар учун идишлар",
  "Ресторанлар учун идишлар Тошкентда",
  "Ресторанлар учун мебел",
  "Ресторанлар учун мебел Тошкентда",
  "Ресторанлар учун тозалаш воситалари",
  "Ресторанлар учун тозалаш воситалари Тошкентда",
  "Ресторанлар учун таъмирлаш ва техник хизмат кўрсатиш",
  "Ресторанлар учун таъмирлаш ва техник хизмат кўрсатиш Тошкентда",
  "Ресторан бошқарув тизими",
  "Ресторан учун консалтинг",
  "Ресторан учун консалтинг Тошкентда",
  "Тошкентдаги меҳмонхоналар, ресторанлар, барлар учун хизматлар",
  "Тошкентда ҲоРеCа учун хизмат кўрсатувчи",
  "Тошкентда ҲоРеCа учун товарларнинг улгуржи савдоси",
  "Тошкентда ҲоРеCа учун профессионал жиҳозлар",
  "Тошкентда ҲоРеCа учун инвентар",
  "ҲоРеCа учун чегирмалар",
  "ҲоРеCа учун аксиялар",
  "ҲоРеCа учун товарлар йетказиб бериш",
  "ҲоРеCа учун интернет-дўкон",
  "ҲоРеCа учун блог",


  "HORECA suppliers",
  "HORECA partnerships",
  "HORECA partnerships in Tashkent",
  "HORECA partnerships in Uzbekistan",
  "Hotel restaurant catering suppliers",
  "HORECA industry collaboration",
  "B2B HORECA suppliers",
  "HORECA equipment wholesale",
  "Restaurant supply chain",
  "Hospitality suppliers",
  "Food and beverage suppliers",
  "HORECA product distribution",
  "HORECA procurement",
  "HORECA logistics solutions",
  "Catering service providers",
  "Hospitality and catering supplies",

  "Поставщики HORECA",
  "Сотрудничество в сфере HORECA",
  "Сотрудничество в сфере HORECA в Ташкенте",
  "Сотрудничество в сфере HORECA в Узбекистане",
  "Поставки для гостиниц и ресторанов",
  "Поставщики для индустрии HORECA",
  "B2B поставщики HORECA",
  "Оборудование для HORECA оптом",
  "Цепочка поставок для ресторанов",
  "Поставщики для отелей и ресторанов",
  "Поставщики продуктов питания и напитков",
  "Дистрибуция продукции HORECA",
  "Закупки для HORECA",
  "Логистические решения для HORECA",
  "Поставщики кейтеринга",
  "Оборудование и расходные материалы для гостиниц и ресторанов",

  "HORECA hamkorlik",
  "Mehmonxona va restoran yetkazib beruvchilar",
  "HORECA sohasidagi hamkorlar",
  "B2B HORECA yetkazib berish",
  "HORECA uskunalari ulgurji savdo",
  "Restoran ta'minot zanjiri",
  "Mehmonxona ta'minotchilari",
  "Oziq-ovqat va ichimlik yetkazib beruvchilar",
  "HORECA mahsulotlarini tarqatish",
  "HORECA xarid qilish",
  "HORECA logistika yechimlari",
  "Catering xizmatlari yetkazib berish",
  "Mehmonxona va restoran uskunalari",

  "HORECA ҳамкорлик",
  "Меҳмонхона ва ресторан етказиб берувчилар",
  "HORECA соҳасидаги ҳамкорлар",
  "B2B HORECA етказиб бериш",
  "HORECA ускуналари улгуржи савдо",
  "Ресторан таъминот занжири",
  "Меҳмонхона таъминотчилари",
  "Озиқ-овқат ва ичимлик етказиб берувчилар",
  "HORECA маҳсулотларини тарқатиш",
  "HORECA харид қилиш",
  "HORECA логистика ечимлари",
  "Кейтеринг хизматлари етказиб бериш",
  "Меҳмонхона ва ресторан ускуналари",

  "Mehmonxona qanday quriladi",
  "Mehmonxona qurish bo'yicha konsultatsiya",
  "Mehmonxona qurish bo'yicha maslahat",
  "Horeca supply",
  "Horeca partners",
  "Mehmonxona biznesi qanday ochsa bo'ladi",
  "Mehmonxona biznesini ochish uchun nimalarga e'tibor berish kerak",
  "Mehmonxona biznesi",
  "Mehmonxona biznesi nima",
  "Mehmonxona biznesini qanday tashkil qilish mumkin",
  "Mehmonxona uchun kerakli buyumlarni qayerdan olish kerak",
  "Mehmonxona uchun kerakli narsalarni qayerdan olish kerak",
  "Necha pulga mehmonxona ochish mumkin",
  "Qanday qilib mehmonxona biznesini yutirish mumkin",
  "Xodimlarni qanday qilib o'qitish mumkin",
  "Mehmonxona xodimlari uchun treninglar",
  "Mehmonxona xavfsizligi",
  "Qancha pul bilan mehmonxona biznesini ochish mumkin",
  "Qancha pul bilan mehmonxona biznesini yuritish mumkin",
  "Biznes konsultatsiya",
  "Horeca konsultatsiya",
  "Mehmonxona sohasi bo'yicha konsultatsiya",

  "Как построить гостиницу",
  "Консультация по строительству гостиницы",
  "Совет по строительству гостиницы",
  "Поставки Horeca",
  "Партнеры Horeca",
  "Как открыть гостиничный бизнес",
  "На что обратить внимание при открытии гостиничного бизнеса",
  "Гостиничный бизнес",
  "Что такое гостиничный бизнес",
  "Как организовать гостиничный бизнес",
  "Где купить необходимые предметы для гостиницы",
  "Где приобрести необходимые вещи для гостиницы",
  "За какую сумму можно открыть гостиницу",
  "Как сделать гостиничный бизнес успешным",
  "Как обучить сотрудников",
  "Тренинги для гостиничных сотрудников",
  "Безопасность гостиницы",
  "С какой суммой можно открыть гостиничный бизнес",
  "С какой суммой можно вести гостиничный бизнес",
  "Бизнес-консультация",
  "Horeca консультация",
  "Консультация в гостиничной сфере",

  "How to build a hotel",
  "Hotel construction consultation",
  "Advice on hotel construction",
  "Horeca supply",
  "Horeca partners",
  "How to start a hotel business",
  "What to consider when starting a hotel business",
  "Hotel business",
  "What is a hotel business",
  "How to organize a hotel business",
  "Where to get necessary items for a hotel",
  "Where to buy essential things for a hotel",
  "How much does it cost to open a hotel",
  "How to make a hotel business successful",
  "How to train staff",
  "Training for hotel staff",
  "Hotel security",
  "How much money is needed to open a hotel business",
  "How much money is required to run a hotel business",
  "Business consultation",
  "Horeca consultation",
  "Consultation in the hotel industry",

  "Меҳмонхона қандай қурилади",
  "Меҳмонхона қуриш бўйича консультация",
  "Меҳмонхона қуриш бўйича маслаҳат",
  "Horeca етказиб бериш",
  "Horeca шериклари",
  "Меҳмонхона бизнеси қандай очиш мумкин",
  "Меҳмонхона бизнесини очиш учун нималарга эътибор бериш керак",
  "Меҳмонхона бизнеси",
  "Меҳмонхона бизнеси нима",
  "Меҳмонхона бизнесини қандай ташкил қилиш мумкин",
  "Меҳмонхона учун керакли буюмларни қаердан олиш керак",
  "Меҳмонхона учун керакли нарсаларни қаердан олиш керак",
  "Неча пулга меҳмонхона очиш мумкин",
  "Қандай қилиб меҳмонхона бизнесини юритиш мумкин",
  "Ходимларни қандай қилиб ўқитиш мумкин",
  "Меҳмонхона ходимлари учун тренинглар",
  "Меҳмонхона хавфсизлиги",
  "Қанча пул билан меҳмонхона бизнесини очиш мумкин",
  "Қанча пул билан меҳмонхона бизнесини юритиш мумкин",
  "Бизнес-консультация",
  "Horeca консультация",
  "Меҳмонхона соҳаси бўйича консультация",

  "Restoran qanday quriladi",
  "Restoran qurish bo'yicha konsultatsiya",
  "Restoran qurish bo'yicha maslahat",
  "Restoran biznesi qanday ochsa bo'ladi",
  "Restoran biznesini ochish uchun nimalarga e'tibor berish kerak",
  "Restoran biznesi",
  "Restoran biznesi nima",
  "Restoran biznesini qanday tashkil qilish mumkin",
  "Restoran uchun kerakli buyumlarni qayerdan olish kerak",
  "Restoran uchun kerakli narsalarni qayerdan olish kerak",
  "Necha pulga restoran ochish mumkin",
  "Qanday qilib restoran biznesini yutirish mumkin",
  "Restoran xodimlari uchun treninglar",
  "Restoran xavfsizligi",
  "Qancha pul bilan restoran biznesini ochish mumkin",
  "Qancha pul bilan restoran biznesini yuritish mumkin",
  "Restoran sohasi bo'yicha konsultatsiya",

  "Как построить ресторан",
  "Консультация по строительству ресторана",
  "Совет по строительству ресторана",
  "Как открыть ресторанный бизнес",
  "На что обратить внимание при открытии ресторанного бизнеса",
  "Ресторанный бизнес",
  "Что такое ресторанный бизнес",
  "Как организовать ресторанный бизнес",
  "Где купить необходимые предметы для ресторана",
  "Где приобрести необходимые вещи для ресторана",
  "За какую сумму можно открыть ресторан",
  "Как сделать ресторанный бизнес успешным",
  "Тренинги для сотрудников ресторана",
  "Безопасность ресторана",
  "С какой суммой можно открыть ресторанный бизнес",
  "С какой суммой можно вести ресторанный бизнес",
  "Консультация в ресторанной сфере",

  "How to build a restaurant",
  "Restaurant construction consultation",
  "Advice on restaurant construction",
  "How to start a restaurant business",
  "What to consider when starting a restaurant business",
  "Restaurant business",
  "What is a restaurant business",
  "How to organize a restaurant business",
  "Where to get necessary items for a restaurant",
  "Where to buy essential things for a restaurant",
  "How much does it cost to open a restaurant",
  "How to make a restaurant business successful",
  "Training for restaurant staff",
  "Restaurant security",
  "How much money is needed to open a restaurant business",
  "How much money is required to run a restaurant business",
  "Consultation in the restaurant industry",

  "Ресторан қандай қурилади",
  "Ресторан қуриш бўйича консультация",
  "Ресторан қуриш бўйича маслаҳат",
  "Ресторан бизнеси қандай очиш мумкин",
  "Ресторан бизнесини очиш учун нималарга эътибор бериш керак",
  "Ресторан бизнеси",
  "Ресторан бизнеси нима",
  "Ресторан бизнесини қандай ташкил қилиш мумкин",
  "Ресторан учун керакли буюмларни қаердан олиш керак",
  "Ресторан учун керакли нарсаларни қаердан олиш керак",
  "Неча пулга ресторан очиш мумкин",
  "Қандай қилиб ресторан бизнесини юритиш мумкин",
  "Ресторан ходимлари учун тренинглар",
  "Ресторан хавфсизлиги",
  "Қанча пул билан ресторан бизнесини очиш мумкин",
  "Қанча пул билан ресторан бизнесини юритиш мумкин",
  "Ресторан соҳаси бўйича консультация",
];
